### ISSUE TITLE
beartype.roar.BeartypeDecorWrappeeException

### ISSUE THREAD

**Issue by anisaha1** [albanie/slurm_gpustat#10]
Hi I am getting this error when running slurm_gpustat

```
Traceback (most recent call last):
  File "<>/anaconda3/envs/pytorch-1.6.0/bin/slurm_gpustat", line 5, in <module>
    from slurm_gpustat.slurm_gpustat import main
  File "<>/anaconda3/envs/pytorch-1.6.0/lib/python3.7/site-packages/slurm_gpustat/slurm_gpustat.py", line 378, in <module>
    def occupancy_stats_for_node(node: str) -> dict:
  File "<>/anaconda3/envs/pytorch-1.6.0/lib/python3.7/site-packages/beartype/_decor/main.py", line 391, in beartype
    func_data.reinit(func)
  File "<>/anaconda3/envs/pytorch-1.6.0/lib/python3.7/site-packages/beartype/_decor/_data.py", line 198, in reinit
    func=func, exception_cls=BeartypeDecorWrappeeException)
  File "<>/anaconda3/envs/pytorch-1.6.0/lib/python3.7/site-packages/beartype/_util/func/utilfunccodeobj.py", line 65, in get_func_codeobj
    f'Callable {repr(func)} code object not found '
beartype.roar.BeartypeDecorWrappeeException: Callable <functools._lru_cache_wrapper object at 0x2aaac727bd70> code object not found (e.g., due to being either C-based or a class or object defining the ``__call__()`` dunder method).
```

Any idea how to resolve this?

Conda env configuration:
slurm-gpustat             0.0.11                   pypi_0    pypi
beartype                  0.6.0              pyhd8ed1ab_0    conda-forge

Python 3.7.9

UPDATE:
Downgrading to beartype=0.5.1 solves the issue.

**Comment by albanie** [comment]
Thanks for flagging this @anisaha1 - will take a look.

**Comment by albanie** [comment]
@anisaha1 - things should now work by `pip install --upgrade slurm_gpustat`, but feel free to re-open if you still have issues.
