### ISSUE TITLE
ValueError: 'a100' is not in list

### ISSUE THREAD

**Issue by wuyushuwys** [albanie/slurm_gpustat#21]
Hello, I encounter the ValueError when simply call `slurm_gpustat`. Many thanks for any help.

- Slurm Version 22.05.11
- Python Version 3.11.5

```bash
Traceback (most recent call last):
  File "/XXXXX/bin/slurm_gpustat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/XXXXX//lib/python3.11/site-packages/slurm_gpustat/slurm_gpustat.py", line 789, in main
    all_info(color=args.color, verbose=args.verbose, partition=args.partition)
  File "<@beartype(slurm_gpustat.slurm_gpustat.all_info) at 0x7fb425f10400>", line 70, in all_info
  File "/XXXXX/lib/python3.11/site-packages/slurm_gpustat/slurm_gpustat.py", line 717, in all_info
    avail_table = available(node2gpus_map=resources, states=states, verbose=verbose)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(slurm_gpustat.slurm_gpustat.available) at 0x7fb425f10360>", line 70, in available
  File "/XXXXX/lib/python3.11/site-packages/slurm_gpustat/slurm_gpustat.py", line 667, in available
    resource_idx = [x["type"] for x in node2gpus_map[node_name]].index(gpu_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'a100' is not in list
```

**Comment by ce107** [comment]
A very similar error on RHEL8.3, Slurm 20.02 and Python 3.9.19:
```
$ slurm_gpustat 

Traceback (most recent call last):
  File "/nobackup/users/ce107/miniforge3/envs/slurm-stuff/bin/slurm_gpustat", line 8, in <module>
    sys.exit(main())
  File "/nobackup/users/ce107/miniforge3/envs/slurm-stuff/lib/python3.9/site-packages/slurm_gpustat/slurm_gpustat.py", line 789, in main
    all_info(color=args.color, verbose=args.verbose, partition=args.partition)
  File "<@beartype(slurm_gpustat.slurm_gpustat.all_info) at 0x7ff7564029d0>", line 73, in all_info
  File "/nobackup/users/ce107/miniforge3/envs/slurm-stuff/lib/python3.9/site-packages/slurm_gpustat/slurm_gpustat.py", line 717, in all_info
    avail_table = available(node2gpus_map=resources, states=states, verbose=verbose)
  File "<@beartype(slurm_gpustat.slurm_gpustat.available) at 0x7ff7564028b0>", line 73, in available
  File "/nobackup/users/ce107/miniforge3/envs/slurm-stuff/lib/python3.9/site-packages/slurm_gpustat/slurm_gpustat.py", line 667, in available
    resource_idx = [x["type"] for x in node2gpus_map[node_name]].index(gpu_type)
ValueError: '1,gpu' is not in list

```
